version: '3'
services: 
  db:
    image: mysql:5.6
    ports:
      - "3315:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: 12345*
      MYSQL_PASSWORD: root
    restart: always
    volumes:
      - ./var/data/mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8082:80"
    depends_on:
      - db